### PR TITLE
Attach a friendly filename to dump file downloads

### PR DESCRIPTION
**Pull request by tracernz**
a) Using the crash key makes it easy to keep track of where it came from/view the crash in the web ui
b) Adding a .dmp extension allows it to be opened in MSVS/WinDbg easily

Note: This doesn't fix up existing crash dumps. I should probably write a one-off script to do that? I did hand-edit [this one](http://dronin-autotown.appspot.com/at/crash/ahFzfmRyb25pbi1hdXRvdG93bnIWCxIJQ3Jhc2hEYXRhGICAgJCQi4YIDA) in the cloud console to make sure the approach worked.

Note: I had to change the imports from `google.golang.org/appengine` to `cloud.google.com/go` on my local branch because the former no longer seems to be publicly accessible? So I possibly haven't tested this with the same version that production uses.

### CODE REVIEW

**Comment by dustin** [comment]
Is there any reason to avoid publishing this without worrying about updating the existing data?

**Comment by tracernz** [comment]
No reason.

**Comment by dustin** [comment]
I had to make a small change to this.  Let me know if it works/doesn't work.

**Comment by tracernz** [comment]
Ha, I had that originally, and it didn't work with the latest version of the lib obtained from cloud.google.com/go. Seems really stupid to make a breaking change like that to an API that's been in the wild for some time... :/

**Comment by tracernz** [comment]
I'm not sure that k.String() is the right thing.. :/ Gets ```attachment; filename="/CrashData,6753715042123776.dmp"```
http://dronin-autotown.appspot.com/at/crash/ahFzfmRyb25pbi1hdXRvdG93bnIWCxIJQ3Jhc2hEYXRhGICAgJD9zv8LDA

**Comment by tracernz** [comment]
https://github.com/d-ronin/autotown/blob/07e30d54d99560285ac1ba792bdca957b672a827/web.go#L466
s/k.String/k.Encode/

**Comment by dustin** [comment]
Updated.

**Pull request closed without merging**
