### PR TITLE
Set actuator min/neutral/max to 0 if mixer unused

### PR DESCRIPTION
**Pull request by mlyle**
Necessary because old installations default to 1000/1000/2000 and this
would affect timer re-enable time (for oneshot) and resolution

Fixes d-ronin/dRonin#1019

### CODE REVIEW

**Comment by mlyle** [comment]
Tested in local installation (with commented out code at bottom).  Shows some shortcomings of python API, as adjusting settings objects is quite a pain.

**Comment by dustin** [comment]
This is deployed and  pushed (am'd it)

**Comment by mlyle** [comment]
Shouldn't it merge, too?  I don't know/understand our process here.

**Comment by mlyle** [comment]
Nvm, I see the commit.

**Comment by dustin** [comment]
I've never done the github two commits per change flow except where people
really wanted it. patch+am is quick and easy and cleaner IMO.  I'm
flexible, though.

**Comment by mlyle** [comment]
@dustin You can now pick "squash + commit" on the merge pull down menu in github, so it's less evil (just one commit, no real merge)

For single commits that's what i've been doing.  For contributions with many changes and history that makes sense, I do the mergey thing.

**Pull request closed without merging**
